### ISSUE TITLE
TODO for mainnet

### ISSUE THREAD

**Issue by wjurkowlaniec** [safe-scan-ai/cancer-ai#77]
- [ ] mainnet dashboard
- [x] mainnet wandb 
- [x]  competition_config for mainnet and testnet
- [x] add logging to wandb rewards and weights
- [x] be ready to generate wandb for validators
- [x] find first validator to install and test 
- [x] prepare  announcements
- [x] generate first 5 datasets and launch script for uploading
- [ ] Discord bot for showing competition results
